import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { expect, it } from "vitest";
import "./global-setup.js";
import { demo, git, reportDir, run } from "./support.js";

it("installs user agent files idempotently and checks push decisions", () => {
  const dir = demo("init"); const home = mkdtempSync(join(tmpdir(), "oq-init-home-"));
  const before = git(dir, "status", "--porcelain");
  const first = run("init-first", dir, ["init", "--yes", "--agent", "all"], { home });
  expect(first.status).toBe(0);
  const expected = [".claude/skills/openqodex/SKILL.md", ".claude/settings.json", ".agents/skills/openqodex/SKILL.md", ".codex/hooks.json", ".cursor/skills/openqodex/SKILL.md", ".cline/skills/openqodex/SKILL.md", "Documents/Cline/Rules/openqodex.md"];
  for (const file of expected) expect(readFileSync(join(home, file), "utf8").length).toBeGreaterThan(0);
  const settings = readFileSync(join(home, ".claude/settings.json"), "utf8");
  const second = run("init-second", dir, ["init", "--yes", "--agent", "all"], { home });
  expect(second.status).toBe(0);
  expect(readFileSync(join(home, ".claude/settings.json"), "utf8")).toBe(settings);
  expect(git(dir, "status", "--porcelain")).toBe(before);
  const command = (JSON.parse(settings) as { hooks: { PreToolUse: { hooks: { command: string }[] }[] } }).hooks.PreToolUse.flatMap((h) => h.hooks)[0]!.command;
  const input = JSON.stringify({ tool_name: "Bash", tool_input: { command: "git push origin main" }, cwd: dir });
  const unreviewed = run("hook-unreviewed", dir, [command], { shell: true, home, input });
  expect(unreviewed.status).toBe(0); expect(unreviewed.stdout).toContain("has not reviewed");
  const b = run("hook-review-brief", dir, ["review", "--agent"], { home }); expect(b.status).toBe(0);
  const path = reportDir(dir);
  const id = (JSON.parse(readFileSync(join(path, "manifest.json"), "utf8")) as { change_id: string }).change_id;
  const candidates = JSON.parse(readFileSync(join(path, "candidates.json"), "utf8")) as { id: string }[];
  writeFileSync(join(path, "agent-findings.json"), JSON.stringify({ version: 1, change_id: id, summary: "Reviewed", findings: [], dropped: candidates.map((c) => ({ candidate: c.id, reason: "Not actionable" })) }));
  expect(run("hook-review-finalize", dir, ["review", "--finalize"], { home }).status).toBe(0);
  const reviewed = run("hook-reviewed", dir, [command], { shell: true, home, input });
  expect(reviewed.status).toBe(0); expect(reviewed.stdout).not.toContain("permissionDecision");
  writeFileSync(join(dir, ".openqodex.yaml"), "review:\n  block_on_severity: critical\n");
  const denied = run("hook-denied", dir, [command], { shell: true, home, input });
  expect(denied.status).toBe(0); expect(denied.stdout).toContain('"permissionDecision":"deny"');
}, 600_000);

it("prints the scan in a real pre-push hook and refuses a blocked push", () => {
  const dir = demo("git-hook"); const home = mkdtempSync(join(tmpdir(), "oq-hook-home-"));
  git(dir, "init", "--bare", join(dir, "../hook-remote.git"));
  git(dir, "remote", "add", "origin", join(dir, "../hook-remote.git"));
  expect(run("git-hook-install", dir, ["hook", "install"], { home }).status).toBe(0);
  git(dir, "push", "-u", "origin", "HEAD:main");
  git(dir, "add", "-A"); git(dir, "commit", "-qm", "Planted change");
  const push = run("git-hook-warn-push", dir, ["git push origin HEAD:main"], { shell: true, home });
  expect(push.status).toBe(0); expect(push.stdout + push.stderr).toContain("scanner");
  writeFileSync(join(dir, ".openqodex.yaml"), "review:\n  block_on_severity: critical\n");
  const config = join(dir, "app/config.py");
  const old = readFileSync(config, "utf8");
  writeFileSync(config, old.replace(/sk_live_([A-Za-z0-9])/, (_, c: string) => `sk_live_${c === "A" ? "B" : "A"}`));
  git(dir, "add", "-A"); git(dir, "commit", "-qm", "Enable block");
  const refused = run("git-hook-block-push", dir, ["git push origin HEAD:main"], { shell: true, home });
  expect(refused.status).not.toBe(0);
}, 600_000);
