// Real binaries on tiny planted inputs for the Kubernetes scanners
// (kube-linter, kubeconform) and the Rust dependency scanner (cargo-deny).
// Each case guards the invocation, the output parser, the changed-line
// filter and tool resolution together; the proxy cases hold the network
// promises in docs/scanners.md. Run by the end-to-end config.
import { spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { chmodSync, existsSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir, userInfo } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { afterAll, describe, expect, it } from "vitest";
import { resolveFirst, scan, withLoggingProxy } from "./subprocess-support.js";
import type { Case } from "./subprocess-support.js";

const here = dirname(fileURLToPath(import.meta.url));

// subprocess-support gives every scan a throwaway HOME. Rust lives under the
// real one unless CARGO_HOME and RUSTUP_HOME say otherwise, so they are named
// here, as a developer's shell would have them.
for (const [key, folder] of [["CARGO_HOME", ".cargo"], ["RUSTUP_HOME", ".rustup"]] as const) {
  const real = join(userInfo().homedir, folder);
  if (!process.env[key] && existsSync(real)) process.env[key] = real;
}

// A Deployment whose container runs privileged.
const PRIVILEGED = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: nginx:1.27.3
          securityContext:
            privileged: true
`;

// The same Deployment with a string where an integer goes.
const STRING_REPLICAS = PRIVILEGED.replace("replicas: 1", 'replicas: "2"');

// A Rust project whose Cargo.lock pins smallvec 1.6.0 (RUSTSEC-2021-0003),
// on lines 6 and 7.
const RUST_PROJECT: Record<string, string> = {
  "Cargo.toml": '[package]\nname = "tiny"\nversion = "0.1.0"\nedition = "2021"\n\n[dependencies]\nsmallvec = "=1.6.0"\n',
  "Cargo.lock":
    '# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = "smallvec"\nversion = "1.6.0"\nsource = "registry+https://github.com/rust-lang/crates.io-index"\nchecksum = "1a55ca5f3b68e41c979bf8c46a6f1da892ca4db8f94023ce0bd32407573b1ac0"\n\n[[package]]\nname = "tiny"\nversion = "0.1.0"\ndependencies = [\n "smallvec",\n]\n',
  "src/main.rs": "fn main() {}\n",
};

// Puts the project's crates in the Cargo cache with the developer's cargo,
// in a copy outside any scan; false when this machine has no cargo.
function primeCargo(files: Record<string, string>): boolean {
  const dir = mkdtempSync(join(tmpdir(), "oq-cargo-prime-"));
  for (const [name, body] of Object.entries(files)) {
    mkdirSync(dirname(join(dir, name)), { recursive: true });
    writeFileSync(join(dir, name), body);
  }
  const fetched = spawnSync("cargo", ["fetch", "--locked", "--manifest-path", join(dir, "Cargo.toml")], { cwd: dir, encoding: "utf8" });
  if (fetched.error) return false;
  if (fetched.status !== 0) throw new Error(`cargo fetch failed: ${fetched.stderr}`);
  return true;
}

const cases: Case[] = [
  { scanner: "kube-linter", rule: "privileged-container", files: { "k8s/web.yaml": PRIVILEGED }, anchor: "k8s/web.yaml" },
  { scanner: "kubeconform", rule: "type", files: { "k8s/web.yaml": STRING_REPLICAS }, anchor: "k8s/web.yaml", network: true },
];

let ran = 0;
let skipped = 0;
afterAll(() => {
  process.stdout.write(`${ran} ran, ${skipped} skipped\n`);
  if (process.env.CI) expect(skipped, "a builtin scanner was skipped under CI").toBe(0);
});

const offline = () => process.env.OPENQODEX_E2E_OFFLINE === "1";

describe("Kubernetes and Rust scanner subprocesses", () => {
  for (const spec of cases)
    it(`${spec.scanner} reports ${spec.rule} on a changed line`, async () => {
      if (spec.network && offline()) {
        skipped++;
        process.stdout.write(`${spec.scanner}: skipped, OPENQODEX_E2E_OFFLINE=1\n`);
        return;
      }
      const result = await scan(spec);
      const status = result.scan.scanners[0]!;
      if (spec.runtime && status.status === "not_installed") {
        expect(status.reason).toMatch(spec.runtime);
        skipped++;
        process.stdout.write(`${spec.scanner}: ${status.reason}\n`);
        return;
      }
      ran++;
      expect(status.status).toBe("ran");
      expect(result.scan.candidates).toContainEqual(expect.objectContaining({ source: spec.scanner, ruleId: spec.rule, filePath: spec.anchor }));
    }, 300_000);

  // kube-linter runs only on the changed files, so a check that needs the
  // object a Service selects, kept in another file, would report every
  // Service changed alone. Those checks are not in OpenQodex's set.
  it("kube-linter reports nothing for a Service changed without the Deployment it selects", async () => {
    const service = "apiVersion: v1\nkind: Service\nmetadata:\n  name: web\nspec:\n  selector:\n    app: web\n  ports:\n    - port: 80\n      targetPort: 8080\n";
    const result = await scan({ scanner: "kube-linter", rule: "", files: { "k8s/service.yaml": service }, anchor: "" });
    expect(result.scan.scanners[0]!.status).toBe("ran");
    expect(result.scan.candidates.filter((c) => c.source === "kube-linter")).toEqual([]);
  }, 300_000);

  // kube-linter skips an object for a check its annotations name; the same
  // text in a YAML comment changes nothing. OpenQodex raises the added
  // annotation itself, since kube-linter then reports nothing there.
  it("kube-linter obeys its ignore annotation, not the same text in a comment, and the annotation is raised", async () => {
    const annotated = PRIVILEGED.replace("  name: web\n", '  name: web\n  annotations:\n    ignore-check.kube-linter.io/privileged-container: "needs the host"\n');
    const commented = PRIVILEGED.replace("  name: web\n", "  name: web\n  # ignore-check.kube-linter.io/privileged-container: needs the host\n");
    const result = await scan({ scanner: "kube-linter", rule: "", files: { "k8s/annotated.yaml": annotated, "k8s/commented.yaml": commented }, anchor: "" });
    expect(result.scan.scanners[0]!.status).toBe("ran");
    const found = result.scan.candidates.filter((c) => c.source === "kube-linter").map((c) => [c.filePath, c.ruleId, c.lineStart]);
    expect(found).toContainEqual(["k8s/commented.yaml", "privileged-container", 20]);
    expect(found).toContainEqual(["k8s/annotated.yaml", "openqodex.suppression-added", 6]);
    expect(found.filter(([file, rule]) => file === "k8s/annotated.yaml" && rule === "privileged-container")).toEqual([]);
    expect(found.filter(([file, rule]) => file === "k8s/commented.yaml" && rule === "openqodex.suppression-added")).toEqual([]);
  }, 300_000);

  // A repo's .kube-linter.yaml can add a check on kube-linter's kubeconform
  // template, which downloads schemas from any URL it names and makes and
  // writes a cache folder wherever it says. OpenQodex passes its own config,
  // so the planted one neither fetches, nor writes, nor replaces the checks.
  it("kube-linter ignores a planted .kube-linter.yaml that would fetch a URL and write a folder", async () => {
    await resolveFirst("kube-linter");
    const planted = join(tmpdir(), `oq-planted-cache-${randomBytes(6).toString("hex")}`);
    const config = [
      "customChecks:",
      "  - name: planted",
      "    template: kubeconform",
      "    params:",
      '      schemaLocations: ["https://example.com/{{ .ResourceKind }}.json"]',
      `      cache: ${planted}`,
      "checks:",
      "  doNotAutoAddDefaults: true",
      "  include: [planted]",
      "",
    ].join("\n");
    const { result, hosts } = await withLoggingProxy(() =>
      scan({ scanner: "kube-linter", rule: "", files: { ".kube-linter.yaml": config, "k8s/web.yaml": PRIVILEGED }, anchor: "" }),
    );
    expect(result.scan.scanners[0]!.status).toBe("ran");
    expect(result.scan.candidates).toContainEqual(expect.objectContaining({ source: "kube-linter", ruleId: "privileged-container" }));
    expect(hosts).toEqual([]);
    expect(existsSync(planted)).toBe(false);
  }, 300_000);

  // kubeconform downloads schemas from the pinned commit only, and caches
  // them under the OpenQodex home: the second run opens no connection.
  it("kubeconform opens raw.githubusercontent.com on a cold cache and nothing on a warm one", async () => {
    if (offline()) return;
    await resolveFirst("kubeconform");
    // The schema cache of the pinned commit, emptied so the first run is cold.
    const recipe = JSON.parse(readFileSync(join(here, "..", "toolchain.json"), "utf8")).tools.kubeconform;
    rmSync(join(process.env.OPENQODEX_HOME!, "cache", "kubeconform", recipe.schemas.commit), { recursive: true, force: true });
    const spec: Case = { scanner: "kubeconform", rule: "", files: { "k8s/web.yaml": STRING_REPLICAS }, anchor: "" };
    const cold = await withLoggingProxy(() => scan(spec));
    expect(cold.result.scan.scanners[0]!.status, cold.result.scan.scanners[0]!.reason ?? "").toBe("ran");
    expect(cold.result.scan.candidates).toContainEqual(expect.objectContaining({ source: "kubeconform", ruleId: "type", lineStart: 6 }));
    expect(cold.hosts).toEqual(["raw.githubusercontent.com"]);
    const warm = await withLoggingProxy(() => scan(spec));
    expect(warm.result.scan.candidates).toContainEqual(expect.objectContaining({ source: "kubeconform", ruleId: "type", lineStart: 6 }));
    expect(warm.hosts).toEqual([]);
  }, 300_000);

  // cargo-deny on a Cargo.lock that pins smallvec 1.6.0. Its crates are put
  // in the Cargo cache first, as on a machine that built the project once:
  // OpenQodex never downloads them.
  it("cargo-deny reports RUSTSEC-2021-0003 on the changed Cargo.lock entry", async () => {
    if (offline()) {
      skipped++;
      process.stdout.write("cargo-deny: skipped, OPENQODEX_E2E_OFFLINE=1\n");
      return;
    }
    const primed = primeCargo(RUST_PROJECT);
    const result = await scan({ scanner: "cargo-deny", rule: "", files: RUST_PROJECT, anchor: "" });
    const status = result.scan.scanners[0]!;
    if (status.status === "not_installed") {
      expect(status.reason).toMatch(/^needs Cargo/);
      expect(primed).toBe(false);
      skipped++;
      process.stdout.write(`cargo-deny: ${status.reason}\n`);
      return;
    }
    ran++;
    expect(status.status, status.reason ?? "").toBe("ran");
    expect(result.scan.candidates).toContainEqual(expect.objectContaining({ source: "cargo-deny", ruleId: "RUSTSEC-2021-0003", filePath: "Cargo.lock", lineStart: 6, lineEnd: 7 }));
  }, 300_000);

  // osv-scanner (through osv.dev) and cargo-deny (through the RustSec
  // database) both report RUSTSEC-2021-0003 on smallvec's Cargo.lock entry.
  // The report keeps one candidate, the higher severity, and names the other
  // scanner on it.
  it("osv-scanner and cargo-deny on one RustSec advisory leave one candidate that names the other", async () => {
    if (offline() || !primeCargo(RUST_PROJECT)) return;
    const result = await scan({ scanner: "osv-scanner", also: ["cargo-deny"], rule: "", files: RUST_PROJECT, anchor: "" });
    for (const row of result.scan.scanners) expect(row.status, `${row.scanner}: ${row.reason ?? ""}`).toBe("ran");
    const advisory = result.scan.candidates.filter((c) => c.ruleId === "RUSTSEC-2021-0003");
    expect(advisory).toHaveLength(1);
    expect(advisory[0]).toMatchObject({ source: "osv-scanner", filePath: "Cargo.lock", lineStart: 6, lineEnd: 7, alsoReportedBy: ["cargo-deny:RUSTSEC-2021-0003"] });
  }, 300_000);

  // The project can name a rustc or a rustc wrapper and a source replacement
  // (.cargo/config.toml), a toolchain to install (rust-toolchain.toml), and
  // advisory database URLs, a database folder and ignores (deny.toml). None
  // of them may run, fetch, write or hide anything: the only connection is
  // the RustSec database on github.com.
  it("cargo-deny opens github.com only and obeys nothing the project's cargo, toolchain or deny files name", async () => {
    if (offline() || !primeCargo(RUST_PROJECT)) return;
    await resolveFirst("cargo-deny");
    const scratch = mkdtempSync(join(tmpdir(), "oq-cargo-planted-"));
    const marker = join(scratch, "ran");
    const wrapper = join(scratch, "wrapper.sh");
    writeFileSync(wrapper, `#!/bin/sh\ntouch '${marker}'\nexec "$@"\n`);
    chmodSync(wrapper, 0o755);
    const plantedDb = join(scratch, "planted-db");
    const toolchains = () => (process.env.RUSTUP_HOME && existsSync(join(process.env.RUSTUP_HOME, "toolchains")) ? readdirSync(join(process.env.RUSTUP_HOME, "toolchains")).sort() : []);
    const before = toolchains();
    const files = {
      ...RUST_PROJECT,
      ".cargo/config.toml": `[build]\nrustc = "${wrapper}"\nrustc-wrapper = "${wrapper}"\n\n[source.crates-io]\nreplace-with = "planted"\n\n[source.planted]\nregistry = "sparse+https://planted.example.com/index/"\n`,
      "rust-toolchain.toml": '[toolchain]\nchannel = "1.70.0"\n',
      "deny.toml": `[advisories]\ndb-urls = ["https://planted.example.com/advisory-db"]\ndb-path = "${plantedDb}"\nignore = ["RUSTSEC-2021-0003"]\n`,
    };
    const { result, hosts } = await withLoggingProxy(() => scan({ scanner: "cargo-deny", rule: "", files, anchor: "" }));
    expect(result.scan.scanners[0]!.status, result.scan.scanners[0]!.reason ?? "").toBe("ran");
    expect(result.scan.candidates).toContainEqual(expect.objectContaining({ source: "cargo-deny", ruleId: "RUSTSEC-2021-0003", filePath: "Cargo.lock" }));
    expect(hosts).toEqual(["github.com"]);
    expect(existsSync(marker)).toBe(false);
    expect(existsSync(plantedDb)).toBe(false);
    expect(toolchains()).toEqual(before);
  }, 300_000);

  it("cargo-deny names crates missing from the Cargo cache and downloads none of them", async () => {
    if (offline() || !primeCargo(RUST_PROJECT)) return;
    await resolveFirst("cargo-deny");
    // itoa 0.1.1 from 2015: in no cache unless this machine built a project with it.
    const lock = '# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = "itoa"\nversion = "0.1.1"\nsource = "registry+https://github.com/rust-lang/crates.io-index"\nchecksum = "ae3088ea4baeceb0284ee9eea42f591226e6beaecf65373e41b38d95a1b8e7a1"\n\n[[package]]\nname = "miss"\nversion = "0.1.0"\ndependencies = [\n "itoa",\n]\n';
    const files = { "Cargo.toml": '[package]\nname = "miss"\nversion = "0.1.0"\nedition = "2021"\n\n[dependencies]\nitoa = "=0.1.1"\n', "Cargo.lock": lock, "src/main.rs": "fn main() {}\n" };
    const { result, hosts } = await withLoggingProxy(() => scan({ scanner: "cargo-deny", rule: "", files, anchor: "" }));
    expect(result.scan.scanners[0]).toMatchObject({ status: "failed" });
    expect(result.scan.scanners[0]!.reason).toMatch(/the crates of Cargo\.lock are not all in your Cargo cache .*itoa v0\.1\.1.*run `cargo fetch`/);
    expect(hosts).toEqual(["github.com"]);
  }, 300_000);

  it("cargo-deny is skipped with a plain reason when offline", async () => {
    process.env.OPENQODEX_OFFLINE = "1";
    try {
      const result = await scan({ scanner: "cargo-deny", rule: "", files: RUST_PROJECT, anchor: "" });
      expect(result.scan.scanners[0]).toMatchObject({ status: "disabled", reason: "offline, advisory database downloads are off" });
    } finally {
      delete process.env.OPENQODEX_OFFLINE;
    }
  }, 300_000);

  it("kubeconform is skipped with a plain reason when offline", async () => {
    process.env.OPENQODEX_OFFLINE = "1";
    try {
      const result = await scan({ scanner: "kubeconform", rule: "", files: { "k8s/web.yaml": STRING_REPLICAS }, anchor: "" });
      expect(result.scan.scanners[0]).toMatchObject({ status: "disabled", reason: "offline, schema downloads are off" });
    } finally {
      delete process.env.OPENQODEX_OFFLINE;
    }
  }, 300_000);
});
